### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by MetaRiser** [HKUDS/GraphPro#2]
I encountered some issues while reproducing your code.
![image](https://github.com/HKUDS/GraphPro/assets/84331471/061a8c1c-c028-4bdb-b9f5-a7330e785d56)

**Comment by yuh-yang** [comment]
Hi!

Would you share which script you are running and how?

**Comment by MetaRiser** [comment]
I run the pretraining code you provided directly
python pretrain.py --data_path dataset/taobao --exp_name pretrain --phase pretrain --log 1 --device cuda:0 --model GraphPro --lr 1e-3 --edge_dropout 0.5

**Comment by yuh-yang** [comment]
Hi,

I have updated the code to fix this bug. Thanks for your feedback!
